### ISSUE TITLE
The logged_actions table is not updating

### ISSUE THREAD

**Issue by wondie** [2ndQuadrant/audit-trigger#24]
I created logged_actions using the sql in this repository but nothing happens when I make insert and update to the database with both postgres user and another user that is not super user. Is there anything I am missing?

**Comment by akikoskinen** [comment]
Did you call the `audit_table` function for the tables you want to be logged?

**Comment by wondie** [comment]
Oh I see what I was missing. The good thing is that I will start working on it in the coming months. Thank you!
