### ISSUE TITLE
License and authors info missing

### ISSUE THREAD

**Issue by hubertlepicki** [2ndQuadrant/audit-trigger#8]
I want to possibly use and customize this code to build auditing extension for Ruby/Rails/Heroku. I would like to know what the license of this code is, and who are the authors so I can credit them appropriately. Any ideas?

**Comment by nineinchnick** [comment]
I second that, I'm building an audit extension for PHP.

**Comment by ringerc** [comment]
PostgreSQL license; 1815ff7158c9f2882e3798192c00c526633473a0

**Comment by ringerc** [comment]
Re creating framework extensions: It might be a good idea to create an extension control file to turn this into a proper Pg extension if you're going to do that, so it can just be loaded with `CREATE EXTENSION`.

Related: #12
